# Generated by Django 2.2.2 on 2019-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0003_auto_20190714_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryInfo_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundry_services', models.CharField(max_length=200)),
            ],
        ),
    ]
