# Generated by Django 2.2.2 on 2019-07-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0004_laundryinfo_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=200)),
            ],
        ),
    ]
