# Generated by Django 2.2.2 on 2019-07-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0008_auto_20190720_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='delivery_city',
            field=models.TextField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundry',
            name='pickup_city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
