# Generated by Django 2.2.2 on 2019-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0009_auto_20190720_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundry',
            old_name='delivery_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='laundry',
            old_name='pickup_address',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='laundry',
            name='delivery_slot',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundry',
            name='pickup_slot',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
