# Generated by Django 2.2.2 on 2019-07-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0011_auto_20190720_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='bill_amount',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundry',
            name='quan',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
