# Generated by Django 2.2.2 on 2019-07-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0012_auto_20190720_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='laundry',
            name='quan',
        ),
    ]
