# Generated by Django 2.2.2 on 2019-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0013_auto_20190720_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundry',
            name='mobile',
        ),
        migrations.AddField(
            model_name='laundry',
            name='pay',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
