# Generated by Django 2.2.2 on 2019-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0015_auto_20190725_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartvalue',
            old_name='bill_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='laundry',
            name='bill_amount',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
