# Generated by Django 2.2.2 on 2019-07-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0016_auto_20190726_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartvalue',
            old_name='amount',
            new_name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='laundry',
            name='bill_amount',
        ),
    ]
