# Generated by Django 2.2.2 on 2019-07-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0017_auto_20190726_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartvalue',
            old_name='bill_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='laundry',
            name='bill',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
