# Generated by Django 2.2.2 on 2019-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laundry', '0019_remove_laundry_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartvalue',
            name='quantity',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
